//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employees.Infrastructure.Procedures {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlProcedures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlProcedures() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Employees.Infrastructure.Procedures.SqlProcedures", typeof(SqlProcedures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на insert into departments(name, phone) values (@Name, @Phone);.
        /// </summary>
        internal static string Department_Create {
            get {
                return ResourceManager.GetString("Department_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на delete from departments where id = @Id;.
        /// </summary>
        internal static string Department_Delete {
            get {
                return ResourceManager.GetString("Department_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select count(1) from departments where id = @Id;.
        /// </summary>
        internal static string Department_Exists {
            get {
                return ResourceManager.GetString("Department_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select * from departments;.
        /// </summary>
        internal static string Department_GetAll {
            get {
                return ResourceManager.GetString("Department_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select * from departments where id = @Id;.
        /// </summary>
        internal static string Department_GetById {
            get {
                return ResourceManager.GetString("Department_GetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на update departments set
        ///                     name = coalesce(@Name, name),
        ///                     phone = coalesce(@Phone, phone)
        ///where id = @Id;.
        /// </summary>
        internal static string Department_Update {
            get {
                return ResourceManager.GetString("Department_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на insert into employees(name, surname, phone, company_id, passport_id, department_id) 
        ///    values (@Name, @Surname, @Phone, @CompanyId, @PassportId, @DepartmentId);.
        /// </summary>
        internal static string Employee_Create {
            get {
                return ResourceManager.GetString("Employee_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на delete from employees where id = @Id;.
        /// </summary>
        internal static string Employee_Delete {
            get {
                return ResourceManager.GetString("Employee_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select count(1) from employees where id = @Id;.
        /// </summary>
        internal static string Employee_Exists {
            get {
                return ResourceManager.GetString("Employee_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select * from employees;.
        /// </summary>
        internal static string Employee_GetAll {
            get {
                return ResourceManager.GetString("Employee_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select * from employees where company_id = @CompanyId;.
        /// </summary>
        internal static string Employee_GetAllByCompanyId {
            get {
                return ResourceManager.GetString("Employee_GetAllByCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select * from employees where department_id = @DepartmendId;.
        /// </summary>
        internal static string Employee_GetAllByDepartmentId {
            get {
                return ResourceManager.GetString("Employee_GetAllByDepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select * from employees where id = @Id;
        ///.
        /// </summary>
        internal static string Employee_GetById {
            get {
                return ResourceManager.GetString("Employee_GetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на update employees set
        ///                     name = coalesce(@Name, name),
        ///                     surname = coalesce(@Surname, surname),
        ///                     phone = coalesce(@Phone, phone),
        ///                     company_id = coalesce(@CompanyId, company_id),
        ///                     passport_id = coalesce(@PassportId, passport_id),
        ///                     department_id = coalesce(@DepartmentId, department_id)
        ///where id = @Id;.
        /// </summary>
        internal static string Employee_Update {
            get {
                return ResourceManager.GetString("Employee_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на insert into passports(type, phone) values (@Type, @Phone);.
        /// </summary>
        internal static string Passport_Create {
            get {
                return ResourceManager.GetString("Passport_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на delete from passports where id = @Id;.
        /// </summary>
        internal static string Passport_Delete {
            get {
                return ResourceManager.GetString("Passport_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select count(1) from passports where id = @Id;.
        /// </summary>
        internal static string Passport_Exists {
            get {
                return ResourceManager.GetString("Passport_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select * from passports;.
        /// </summary>
        internal static string Passport_GetAll {
            get {
                return ResourceManager.GetString("Passport_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select * from passports where id = @Id;.
        /// </summary>
        internal static string Passport_GetById {
            get {
                return ResourceManager.GetString("Passport_GetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на update passports set
        ///                     type = coalesce(@Type, type),
        ///                     phone = coalesce(@Phone, phone)
        ///where id = @Id;.
        /// </summary>
        internal static string Passport_Update {
            get {
                return ResourceManager.GetString("Passport_Update", resourceCulture);
            }
        }
    }
}
